### ISSUE TITLE
Improve testimonial page design for smartphone

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino.io#155]
The design is little broken in my iPhone. The screenshot is created by Chrome's Developer Tools. 

<img width="460" alt="Screen Shot 2021-01-15 at 8 57 27" src="https://user-images.githubusercontent.com/6237050/104663287-016dd300-5710-11eb-978e-cfab3060face.png">

**Comment by mosabua** [comment]
We are aware and @aliloney is already working on it

**Comment by ebyhr** [comment]
Fixed by #156
