### ISSUE TITLE
JDBC driver 

### ISSUE THREAD

**Issue by irvcaza** [trinodb/trino.io#326]
Trying to download [Trino JDBC driver](https://trino.io/docs/current/installation/jdbc.html) from the [Resources web page]( https://trino.io/resources.html) gives 404 File not found:

Full info of the error 

```
404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

[Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.
```

I don't know the best place to report this, if it’s not here, please let me know.

**Comment by mosabua** [comment]
This is an invalid link to the documentation page that changed. I will create a PR to fix this.

in the meantime

* https://trino.io/download.html
* https://trino.io/docs/current/client/jdbc.html
